language: node_js
node_js:
- '14'
script:
- npm run build

deploy:
  - provider: s3
    access_key_id: AKIARN6JP35RSZQH5JWJ
    secret_access_key:
      secure: QXByM4JkEHLXBiKjE0YLWSfqKF4s2u8Bmf4eDysLr4Z+rlTC1INLz4WRnG90g0dZpBE3Zyc9j9Dnp6ODbvVMpaT8c6WBxfPx97/nWDzmJhTDEmF9OMobdPHrSZyylZ3tcztLlQe/Uqzo8w8viOMFgm94kNr0zdEwUBKrGQSwiZzac3EI34QyBXbdiQJHsnhhnKCP6x6fi15eWPE2zkxZhcuX2FdHKcJIjTx1gCuc2RQqOOA6oSBJIhREga/AuZCJ8iXDFCjvG9SxJSQY83uv7q2Y3N1foxclQGOFvERsawLtmbY1bkG8Fsiw2xAypg4+uEZ5u8sMd1ZEOVwN/DUjXqVwbnkEtESXdMH9YgAEenzPjoXicGYDhxErErv7AizTLHoNW5pdxed5efsz3UD0BqFTBN6UuaUCbd+9HhYMjeazRdut+yTTdu25m9SuqJrt6aMERR2eaMhvBima8rdtx/6vlPy7n+LQ0j7khyXS31rdUePevO2ulGR1pcWUhYrWzwm/gxF5w8htXYcYhiFkThUBNpBDnZcRocj8XzJWlSWhE5RpxqJQ6VYThkI8hsDkaL6CUCwtJT9+ULcFtDU/bG6S8mqvlCX2nzVvb6BaXmg3VXs0VB7nemkIMD0mXp/L+8wGdCkfiH0uIlyMfrmjAQA8UEMhv3wF/8LAdSUNHGg=
    bucket: acb.gg
    on:
      repo: brownac/acb.gg
    skip_cleanup: 'true'
    local_dir: build
  - provider: s3
    access_key_id: AKIARN6JP35RSZQH5JWJ
    secret_access_key:
      secure: QXByM4JkEHLXBiKjE0YLWSfqKF4s2u8Bmf4eDysLr4Z+rlTC1INLz4WRnG90g0dZpBE3Zyc9j9Dnp6ODbvVMpaT8c6WBxfPx97/nWDzmJhTDEmF9OMobdPHrSZyylZ3tcztLlQe/Uqzo8w8viOMFgm94kNr0zdEwUBKrGQSwiZzac3EI34QyBXbdiQJHsnhhnKCP6x6fi15eWPE2zkxZhcuX2FdHKcJIjTx1gCuc2RQqOOA6oSBJIhREga/AuZCJ8iXDFCjvG9SxJSQY83uv7q2Y3N1foxclQGOFvERsawLtmbY1bkG8Fsiw2xAypg4+uEZ5u8sMd1ZEOVwN/DUjXqVwbnkEtESXdMH9YgAEenzPjoXicGYDhxErErv7AizTLHoNW5pdxed5efsz3UD0BqFTBN6UuaUCbd+9HhYMjeazRdut+yTTdu25m9SuqJrt6aMERR2eaMhvBima8rdtx/6vlPy7n+LQ0j7khyXS31rdUePevO2ulGR1pcWUhYrWzwm/gxF5w8htXYcYhiFkThUBNpBDnZcRocj8XzJWlSWhE5RpxqJQ6VYThkI8hsDkaL6CUCwtJT9+ULcFtDU/bG6S8mqvlCX2nzVvb6BaXmg3VXs0VB7nemkIMD0mXp/L+8wGdCkfiH0uIlyMfrmjAQA8UEMhv3wF/8LAdSUNHGg=
    bucket: www.acb.gg
    on:
      repo: brownac/acb.gg
    skip_cleanup: 'true'
    local_dir: build
