name: Build and deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node-version: [20.10.0]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages, test and build artifacts
        run: |
          npm i -D
          npm run build
        env:
          CI: true
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifacts
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy artifacts to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          ./build s3://acb.gg \
          --recursive \
          --acl public-read \
          --region ap-southeast-2